name: Azure deployment

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
      - '.github/workflows/azure-deploy.yml'

jobs:
  deploy:
    name: Bicep -> staging -> production swap
    environment: pippa-environemnt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          region: westeurope
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: subscription
          template: infra/main.bicep
          deploymentName: pippa-chatapp

      - name: Swap slot after health-check
        run: |
          az webapp deployment slot swap \
            --resource-group pippaoflondon-rg \
            --name pippaoflondonai \
            --slot staging \
            --target-slot production